export const BD_HOST= "BD_HOST"
export const BD_USER= "BD_USER"
export const BD_PASSWORD= "BD_PASSWORD"
export const DB_TYPE="DB_TYPE"
export const BD_NAME= "BD_NAME"
export const BD_PORT= "BD_PORT"
export const APP_PORT= "APP_PORT"

export const URL_FRONTEND ="URL_FRONTEND"
export const URL_VALIDACION_INSCRIPCION ="URL_VALIDACION_INSCRIPCION"
export const MAIL_HOST ="MAIL_HOST"
export const MAIL_USER ="MAIL_USER"
export const MAIL_PASSWORD ="MAIL_PASSWORD"
export const MAIL_FROM ="MAIL_FROM"
export const MAIL_PORT="MAIL_PORT"