export const BD_HOST= "BD_HOST"
export const BD_USER= "BD_USER"
export const BD_PASSWORD= "BD_PASSWORD"
export const DB_TYPE="DB_TYPE"
export const BD_NAME= "BD_NAME"
export const BD_PORT= "BD_PORT"
export const APP_PORT= "APP_PORT"